config/routes.rb
Rails.application.routes.draw do
  resources :descriptions
  resources :films do
    collection do
      get :search
    end
  end
  resources :film_companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :film
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :film_company
  has_one :description

  def self.search(params)
    result = Film.includes(:film_company, :description).references(:film_company, :description)

    if params['name'].present?
      result = result.where('films.name = ?', params['name'])
    end

    if params['director'].present?
      result = result.where('films.director = ?', params['director'])
    end

    if params['film_company'].present?
      result = result.where('film_companies.name = ?', params['film_company'])
    end

    if params['description'].present?
      result = result.where('descriptions.description LIKE ?', "%#{params['description']}%")
    end

    result
  end
end

app/models/film_company.rb
class FilmCompany < ApplicationRecord
  has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  before_action :set_description, only: [:show, :edit, :update, :destroy]

  # GET /descriptions
  # GET /descriptions.json
  def index
    @descriptions = Description.all
  end

  # GET /descriptions/1
  # GET /descriptions/1.json
  def show
  end

  # GET /descriptions/new
  def new
    @description = Description.new
  end

  # GET /descriptions/1/edit
  def edit
  end

  # POST /descriptions
  # POST /descriptions.json
  def create
    @description = Description.new(description_params)

    respond_to do |format|
      if @description.save
        format.html { redirect_to @description, notice: 'Description was successfully created.' }
        format.json { render :show, status: :created, location: @description }
      else
        format.html { render :new }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /descriptions/1
  # PATCH/PUT /descriptions/1.json
  def update
    respond_to do |format|
      if @description.update(description_params)
        format.html { redirect_to @description, notice: 'Description was successfully updated.' }
        format.json { render :show, status: :ok, location: @description }
      else
        format.html { render :edit }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /descriptions/1
  # DELETE /descriptions/1.json
  def destroy
    @description.destroy
    respond_to do |format|
      format.html { redirect_to descriptions_url, notice: 'Description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_description
      @description = Description.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def description_params
      params.require(:description).permit(:film_id, :description, :keywords)
    end
end

app/controllers/film_companies_controller.rb
class FilmCompaniesController < ApplicationController
  before_action :set_film_company, only: [:show, :edit, :update, :destroy]

  # GET /film_companies
  # GET /film_companies.json
  def index
    @film_companies = FilmCompany.all
  end

  # GET /film_companies/1
  # GET /film_companies/1.json
  def show
  end

  # GET /film_companies/new
  def new
    @film_company = FilmCompany.new
  end

  # GET /film_companies/1/edit
  def edit
  end

  # POST /film_companies
  # POST /film_companies.json
  def create
    @film_company = FilmCompany.new(film_company_params)

    respond_to do |format|
      if @film_company.save
        format.html { redirect_to @film_company, notice: 'Film company was successfully created.' }
        format.json { render :show, status: :created, location: @film_company }
      else
        format.html { render :new }
        format.json { render json: @film_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /film_companies/1
  # PATCH/PUT /film_companies/1.json
  def update
    respond_to do |format|
      if @film_company.update(film_company_params)
        format.html { redirect_to @film_company, notice: 'Film company was successfully updated.' }
        format.json { render :show, status: :ok, location: @film_company }
      else
        format.html { render :edit }
        format.json { render json: @film_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /film_companies/1
  # DELETE /film_companies/1.json
  def destroy
    @film_company.destroy
    respond_to do |format|
      format.html { redirect_to film_companies_url, notice: 'Film company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film_company
      @film_company = FilmCompany.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_company_params
      params.require(:film_company).permit(:name, :country)
    end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  def search
    @film_companies = FilmCompany.all
    if params.has_key?('search')
      @films = Film.search(params['search'])
    else
      @films = []
    end
    params['search'] ||= {}
  end
  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Film was successfully created.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Film was successfully updated.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Film was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:name, :year, :director, :film_company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/film_companies_helper.rb
module FilmCompaniesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/descriptions/_form.html.haml
= form_for @description do |f|
  - if @description.errors.any?
    #error_explanation
      %h2= "#{pluralize(@description.errors.count, "error")} prohibited this description from being saved:"
      %ul
        - @description.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :film_id
    = f.text_field :film_id
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :keywords
    = f.text_field :keywords
  .actions
    = f.submit 'Save'

app/views/descriptions/edit.html.haml
%h1 Editing description

= render 'form'

= link_to 'Show', @description
\|
= link_to 'Back', descriptions_path

app/views/descriptions/index.html.haml
%h1 Listing descriptions

%table
  %thead
    %tr
      %th Film name
      %th Description
      %th Keywords
      %th
      %th
      %th

  %tbody
    - @descriptions.each do |description|
      %tr
        %td= description.film.name
        %td= description.description
        %td= description.keywords
        %td= link_to 'Show', description
        %td= link_to 'Edit', edit_description_path(description)
        %td= link_to 'Destroy', description, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Description', new_description_path

app/views/descriptions/new.html.haml
%h1 New description

= render 'form'

= link_to 'Back', descriptions_path

app/views/descriptions/show.html.haml
%p#notice= notice

%p
  %b Film name:
  = @description.film.name
%p
  %b Description:
  = @description.description
%p
  %b Keywords:
  = @description.keywords

= link_to 'Edit', edit_description_path(@description)
\|
= link_to 'Back', descriptions_path

app/views/film_companies/_form.html.haml
= form_for @film_company do |f|
  - if @film_company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@film_company.errors.count, "error")} prohibited this film_company from being saved:"
      %ul
        - @film_company.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :country
    = f.text_field :country
  .actions
    = f.submit 'Save'

app/views/film_companies/edit.html.haml
%h1 Editing film_company

= render 'form'

= link_to 'Show', @film_company
\|
= link_to 'Back', film_companies_path

app/views/film_companies/index.html.haml
%h1 Listing film_companies

%table
  %thead
    %tr
      %th Name
      %th Country
      %th
      %th
      %th

  %tbody
    - @film_companies.each do |film_company|
      %tr
        %td= film_company.name
        %td= film_company.country
        %td= link_to 'Show', film_company
        %td= link_to 'Edit', edit_film_company_path(film_company)
        %td= link_to 'Destroy', film_company, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Film company', new_film_company_path

app/views/film_companies/new.html.haml
%h1 New film_company

= render 'form'

= link_to 'Back', film_companies_path

app/views/film_companies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @film_company.name
%p
  %b Country:
  = @film_company.country

= link_to 'Edit', edit_film_company_path(@film_company)
\|
= link_to 'Back', film_companies_path

app/views/films/_form.html.haml
= form_for @film do |f|
  - if @film.errors.any?
    #error_explanation
      %h2= "#{pluralize(@film.errors.count, "error")} prohibited this film from being saved:"
      %ul
        - @film.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :year
    = f.number_field :year
  .field
    = f.label :director
    = f.text_field :director
  .field
    = f.label :film_company_id
    = f.text_field :film_company_id
  .actions
    = f.submit 'Save'

app/views/films/edit.html.haml
%h1 Editing film

= render 'form'

= link_to 'Show', @film
\|
= link_to 'Back', films_path

app/views/films/index.html.haml
%h1 Listing films

%table
  %thead
    %tr
      %th Name
      %th Year
      %th Director
      %th Film company name
      %th
      %th
      %th

  %tbody
    - @films.each do |film|
      %tr
        %td= film.name
        %td= film.year
        %td= film.director
        %td= film.film_company.name
        %td= link_to 'Show', film
        %td= link_to 'Edit', edit_film_path(film)
        %td= link_to 'Destroy', film, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Film', new_film_path

app/views/films/new.html.haml
%h1 New film

= render 'form'

= link_to 'Back', films_path

app/views/films/search.html.haml
%h1 Search

=form_tag search_films_path(), method: :get do
  %b Film name:
  =text_field_tag 'search[name]', params['search']['name'], id: 'film_name'
  %br
  %b Film companies:
  =select_tag 'search[company]', options_for_select(@film_companies.collect{ |t| t.name }), :include_blank => true
  %br
  %b Director name:
  =text_field_tag 'search[director]', params['search']['director'], id: 'director_name'
  %br
  %b Description:
  =text_field_tag 'search[description]', params['search']['description']
  %br
  =submit_tag 'Search'

%br
=link_to 'Clear inputs of film', '', id: 'clear'

- if @films
  %table
    - @films.each do |film|
      %thead
        %tr
          %th Film name
          %th Film year
          %th Film director
      %tbody
        %tr
          %td= film.name
          %td= film.year
          %td= film.director
    %br

app/views/films/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @film.name
%p
  %b Year:
  = @film.year
%p
  %b Director:
  = @film.director
%p
  %b Film company name:
  = @film.film_company.name

= link_to 'Edit', edit_film_path(@film)
\|
= link_to 'Back', films_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>